#pragma once
#include "glm/glm.hpp"// IWYU pragma: keep
#include "string_view"
#include <cstdint>


namespace squi {
	struct Color {
		uint8_t r;
		uint8_t g;
		uint8_t b;
		uint8_t a;

		Color() = default;
		Color(uint32_t value);
		Color(std::string_view hex);
		Color(uint8_t r, uint8_t g, uint8_t b, uint8_t a = 255);
		Color(int r, int g, int b, int a = 255);
		Color(float r, float g, float b, float a = 1.0f);
		Color(const glm::vec4 &vec);
		static Color css(int r, int g, int b, float a = 1.f);
		static Color rgba(int r, int g, int b, float a = 1.f);
		static Color rgb(int r, int g, int b);
		static Color css(int rgb, float a = 1.f);
		static Color fromHSV(float h, float s, float v, float a = 1.0f);

		[[nodiscard]] operator glm::vec4() const;

		[[nodiscard]] Color transition(const Color &other, float t) const;

		[[nodiscard]] Color mix(const Color &other) const;

		[[nodiscard]] bool operator==(const Color &other) const;

		[[nodiscard]] Color operator*(const float &multiplier) const;

		[[nodiscard]] bool isLight() const;

		static Color transparent;
		static Color black;
		static Color silver;
		static Color gray;
		static Color white;
		static Color maroon;
		static Color red;
		static Color purple;
		static Color fuchsia;
		static Color green;
		static Color lime;
		static Color olive;
		static Color yellow;
		static Color navy;
		static Color blue;
		static Color teal;
		static Color aqua;

		static Color aliceblue;
		static Color antiquewhite;
		static Color aquamarine;
		static Color azure;
		static Color beige;
		static Color bisque;
		static Color blanchedalmond;
		static Color blueviolet;
		static Color brown;
		static Color burlywood;
		static Color cadetblue;
		static Color chartreuse;
		static Color chocolate;
		static Color coral;
		static Color cornflowerblue;
		static Color cornsilk;
		static Color crimson;
		static Color cyan;
		static Color darkblue;
		static Color darkcyan;
		static Color darkgoldenrod;
		static Color darkgray;
		static Color darkgreen;
		static Color darkgrey;
		static Color darkkhaki;
		static Color darkmagenta;
		static Color darkolivegreen;
		static Color darkorange;
		static Color darkorchid;
		static Color darkred;
		static Color darksalmon;
		static Color darkseagreen;
		static Color darkslateblue;
		static Color darkslategray;
		static Color darkslategrey;
		static Color darkturquoise;
		static Color darkviolet;
		static Color deeppink;
		static Color deepskyblue;
		static Color dimgray;
		static Color dimgrey;
		static Color dodgerblue;
		static Color firebrick;
		static Color floralwhite;
		static Color forestgreen;
		static Color gainsboro;
		static Color ghostwhite;
		static Color gold;
		static Color goldenrod;
		static Color greenyellow;
		static Color grey;
		static Color honeydew;
		static Color hotpink;
		static Color indianred;
		static Color indigo;
		static Color ivory;
		static Color khaki;
		static Color lavender;
		static Color lavenderblush;
		static Color lawngreen;
		static Color lemonchiffon;
		static Color lightblue;
		static Color lightcoral;
		static Color lightcyan;
		static Color lightgoldenrodyellow;
		static Color lightgray;
		static Color lightgreen;
		static Color lightgrey;
		static Color lightpink;
		static Color lightsalmon;
		static Color lightseagreen;
		static Color lightskyblue;
		static Color lightslategray;
		static Color lightslategrey;
		static Color lightsteelblue;
		static Color lightyellow;
		static Color limegreen;
		static Color linen;
		static Color magenta;
		static Color mediumaquamarine;
		static Color mediumblue;
		static Color mediumorchid;
		static Color mediumpurple;
		static Color mediumseagreen;
		static Color mediumslateblue;
		static Color mediumspringgreen;
		static Color mediumturquoise;
		static Color mediumvioletred;
		static Color midnightblue;
		static Color mintcream;
		static Color mistyrose;
		static Color moccasin;
		static Color navajowhite;
		static Color oldlace;
		static Color olivedrab;
		static Color orange;
		static Color orangered;
		static Color orchid;
		static Color palegoldenrod;
		static Color palegreen;
		static Color paleturquoise;
		static Color palevioletred;
		static Color papayawhip;
		static Color peachpuff;
		static Color peru;
		static Color pink;
		static Color plum;
		static Color powderblue;
		static Color rebeccapurple;
		static Color rosybrown;
		static Color royalblue;
		static Color saddlebrown;
		static Color salmon;
		static Color sandybrown;
		static Color seagreen;
		static Color seashell;
		static Color sienna;
		static Color skyblue;
		static Color slateblue;
		static Color slategray;
		static Color slategrey;
		static Color snow;
		static Color springgreen;
		static Color steelblue;
		static Color tan;
		static Color thistle;
		static Color tomato;
		static Color turquoise;
		static Color violet;
		static Color wheat;
		static Color whitesmoke;
		static Color yellowgreen;
	};
}// namespace squi
